# Generated by Django 4.2.23 on 2025-12-09 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('default_address_line_1', models.CharField(blank=True, max_length=80, null=True)),
                ('default_address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('default_town_or_city', models.CharField(blank=True, max_length=40, null=True)),
                ('default_post_code', models.CharField(blank=True, max_length=20, null=True)),
                ('default_county', models.CharField(blank=True, max_length=40, null=True)),
                ('default_country', django_countries.fields.CountryField(blank=True, max_length=40, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
