# Generated by Django 4.2.23 on 2025-12-10 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='description',
        ),
        migrations.AddField(
            model_name='recipe',
            name='serving_size',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
